### ISSUE TITLE
logical fallacies

### ISSUE THREAD

**Issue by lookfirst** [dialecticch/router#1]
Just passing on something I learned from a contract expert who looked at this...

```
The code shared contains a logical fallacy, it uses the spot price on chain and requests a minimum % of that spot price but slippage doesn't work like that, if the output you get on chain is XYZ you are going to get XYZ 100%
```

**Comment by decanus** [comment]
I'm not sure I understand what you mean here:

> if the output you get on chain is XYZ you are going to get XYZ 100%

**Comment by alex-ppg** [comment]
Hey @decanus, thanks for looking into this. Let me put some more context to it.

The `swap` function accepts a `slippage` argument that is meant to denote the per mille (‰) deviation in the final output of the swap compared to the expected output of the swap based on `dataForBestExchange`.

This is a logical fallacy because the `dataForBestExchange` fetches the expected output via `amountOutFor` that directly calculates the swap's output based on the current spot price. 

The spot price does not change between output calculation and swap execution, meaning that the "minimum" output will always be satisfied for `[0, 1000]` as  it will in all cases be equivalent to the `amountOut` we calculate.

**Comment by decanus** [comment]
I believe the `amountOutFor` is based on a historical price is it not? I may be completely wrong.

**Comment by lookfirst** [comment]
@decanus Was this resolved? Just curious.
